import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/providers/QueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <QueryProvider>
            <html lang='en' className='min-h-full'>
                <ReactQueryDevtools
                    initialIsOpen={true}
                    buttonPosition='bottom-left'
                    position='top'
                />
                <body className={`${inter.className} h-full`}>{children}</body>
            </html>
        </QueryProvider>
    );
}
